Feature/add group resource
topicuskeyhub/terraform-provider-keyhub pull request #7
Opened 2022-06-01 13:28 UTC by maikelpoot

*Work in progress*

This PR will enable the provider to create groups.

Update should trigger warning and do nothing
Delete should remove the resource from the terraform state, but won't delete from keyhub

Usage:
```hcl
#Create a group
resource "keyhub_group" "new_group" {
  name = "new_keyhub_group"

  # UUID of keyhub user/account
  member {
    uuid = "00000000-0000-0000-0000-000000000000"
    rights = "MANAGER"
  }

  audit_months = ["JANUARY"]

  description = "This group is created by terraform"

  # UUID of the group that should be set as authoring group
  provisioning_auth_groupuuid = "00000000-0000-0000-0000-000000000000"
  membership_auth_groupuuid   = "00000000-0000-0000-0000-000000000000"
  auditing_auth_groupuuid     = "00000000-0000-0000-0000-000000000000"

}
```

2022-06-24 12:46 UTC, hielkehoeve requested changes

2022-06-24 12:46 UTC, hielkehoeve commented on keyhub/resource_group.go
> +	d.Set("uuid", grpUuid.String())
Dit kan niet. d.Id() is geen UUID maar het database ID.
Zie:

[Resource Create](https://github.com/topicuskeyhub/terraform-provider-keyhub/blob/a34c839e3fde504010528047bd0c20b1e5abd2f0/keyhub/resource_group.go#L307)
[Data Read](https://github.com/topicuskeyhub/terraform-provider-keyhub/blob/a34c839e3fde504010528047bd0c20b1e5abd2f0/keyhub/data_source_group.go#L217)

2022-07-12 07:42 UTC, maikelpoot commented on docs/resources/group.md
> +  member {
Nee, typeset betekent dat je de key vaker kunt opgeven. bijv om 2 members aan de group te koppelen: 

```
resource "keyhub_group" "new_group" {
  name = "new_keyhub_group"
  
  # UUID of first keyhub user/account
  member {
    uuid = "00000000-0000-0000-0000-000000000000"
    rights = "MANAGER"
  }

  # UUID of second keyhub user/account
  member {
    uuid = "11111111-1111-1111-1111-111111111111"
    rights = "MANAGER"
  }

}
```

2022-07-15 09:21 UTC, maikelpoot commented
Moved branch to this repo, to continue further development in the branch.

New PR opened: #10

2022-07-15 09:21 UTC, closed without merging